services:
  mysql:
    image: mysql:8.4
    container_name: job-scheduler-mysql
    restart: unless-stopped

    environment:
      MYSQL_DATABASE: job_scheduler
      MYSQL_USER: job_user
      MYSQL_PASSWORD: job_password
      MYSQL_ROOT_PASSWORD: root_password

    ports:
      - "3307:3306"

    volumes:
      - job_scheduler_mysql_data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-uroot",
          "-proot_password"
        ]
      interval: 5s
      timeout: 5s
      retries: 20

  redis:
    image: redis:7-alpine
    container_name: job-scheduler-redis
    restart: unless-stopped

    ports:
      - "6379:6379"

    volumes:
      - job_scheduler_redis_data:/data

    command: redis-server --appendonly yes

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  job_scheduler_mysql_data:
  job_scheduler_redis_data: